[package]
name = "fw-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = "0.1"
aya-log-ebpf = "0.1"
fw-common = { path = "../fw-common" }

[[bin]]
name = "fw-ebpf"
path = "src/main.rs"
