# Rust formatting configuration
# Follows Rule 4: Line Length Limit (80 characters)

max_width = 80
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
